//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qly_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Info
    {
        public int id_BillInfo { get; set; }
        public int id_Bill { get; set; }
        public int id_Food { get; set; }
        public int count_Food { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Food Food { get; set; }
    }
}
