//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qly_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        internal object Category;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Bill_Info = new HashSet<Bill_Info>();
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int id_Food { get; set; }
        public string name_Food { get; set; }
        public int id_Category { get; set; }
        public double price_Food { get; set; }
        public byte[] image_Food { get; set; }
        public string condition_Food { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Info> Bill_Info { get; set; }
        public virtual CategoryFood CategoryFood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
