//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qly_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id_Reservation { get; set; }
        public string name_Guest { get; set; }
        public System.DateTime date_Reservation { get; set; }
        public string phone_Guest { get; set; }
        public Nullable<int> id_Table { get; set; }
    
        public virtual Tablee Tablee { get; set; }
    }
}
